import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  usage: [{type: 'autogenerated', dirName: 'usage'}],
  dev: [{type: 'autogenerated', dirName: 'dev'}],
};

module.exports = sidebars;
